INSERT INTO books (img, price, title, year) VALUES ('fake-url',29.99,'El señor de los anillos', 1954);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',24.99,'Cien años de soledad', 1967);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',19.99,'Harry Potter y la piedra filosofal', 1997);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',15.99,'1984', 1949);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',18.99,'Orgullo y prejuicio', 1813);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',12.99,'La Odisea', 800);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',21.99,'Don Quijote de la Mancha', 1605);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',17.99,'Matar a un ruiseñor', 1960);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',14.99,'La metamorfosis', 1915);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',16.99,'Hamlet', 1603);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',23.99,'Crimen y castigo', 1866);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',20.99,'El Gran Gatsby', 1925);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',22.99,'La Divina Comedia', 1320);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',13.99,'Alicia en el país de las maravillas', 1865);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',26.99,'Anna Karenina', 1877);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',28.99,'Moby Dick', 1851);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',27.99,'Los miserables', 1862);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',25.99,'Rayuela', 1963);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',31.99,'La guerra y la paz', 1869);
INSERT INTO books (img, price, title, year) VALUES ('fake-url',9.99,'El principito', 1943);